import ReactMarkdown from "react-markdown";
import remarkMath from "remark-math";
import rehypeKatex from "rehype-katex";
import { Copy, Check, Sparkles, Download, FileText } from "lucide-react";
import { Button } from "@/components/ui/button";
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface ResultCardProps {
  content: string;
  isLoading: boolean;
  type: 'solve' | 'summarize' | 'mcq';
}

export function ResultCard({ content, isLoading, type }: ResultCardProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const downloadText = () => {
    const element = document.createElement("a");
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = `AI-Study-${type}-${new Date().getTime()}.txt`;
    document.body.appendChild(element);
    element.click();
  };

  if (!content && !isLoading) return null;

  return (
    <AnimatePresence mode="wait">
      {isLoading ? (
        <motion.div
          key="loading"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, scale: 0.95 }}
          className="glass-card rounded-[2rem] p-12 min-h-[300px] flex flex-col items-center justify-center text-center space-y-6"
        >
          <div className="relative">
            <div className="w-20 h-20 rounded-full border-[6px] border-primary/10 animate-[spin_4s_linear_infinite]" />
            <div className="w-20 h-20 rounded-full border-[6px] border-t-primary animate-spin absolute top-0 left-0" />
            <div className="absolute inset-0 flex items-center justify-center">
              <BrainCircuit className="w-10 h-10 text-primary animate-pulse" />
            </div>
          </div>
          <div className="space-y-2">
            <h4 className="text-xl font-display font-bold text-foreground">Analyzing Input...</h4>
            <p className="text-muted-foreground max-w-xs mx-auto">
              Our advanced AI is processing your content to generate the best possible results.
            </p>
          </div>
        </motion.div>
      ) : (
        <motion.div
          key="result"
          initial={{ opacity: 0, y: 30, scale: 0.98, filter: "blur(10px)" }}
          animate={{ opacity: 1, y: 0, scale: 1, filter: "blur(0px)" }}
          transition={{ type: "spring", damping: 25, stiffness: 200 }}
          className="glass-card rounded-[2rem] overflow-hidden group"
        >
          <div className="bg-gradient-to-r from-primary/20 via-accent/10 to-transparent px-10 py-8 flex items-center justify-between border-b border-white/10 backdrop-blur-md">
            <h3 className="font-display font-bold text-2xl text-primary flex items-center gap-4">
              <div className="p-3 bg-primary/20 rounded-2xl shadow-inner">
                <Sparkles className="w-6 h-6" />
              </div>
              Insights & Solutions
            </h3>
            <div className="flex items-center gap-3">
              <Button
                variant="ghost"
                size="sm"
                onClick={downloadText}
                className="hover:bg-primary/10 rounded-2xl h-12 px-5 font-bold"
              >
                <Download className="w-5 h-5 mr-2" />
                Export
              </Button>
              <Button
                variant="secondary"
                size="sm"
                onClick={handleCopy}
                className="rounded-2xl font-bold h-12 px-6 shadow-lg"
              >
                {copied ? (
                  <>
                    <Check className="w-5 h-5 mr-2" />
                    Copied
                  </>
                ) : (
                  <>
                    <Copy className="w-5 h-5 mr-2" />
                    Copy All
                  </>
                )}
              </Button>
            </div>
          </div>
          
          <div className="p-10 md:p-16 overflow-y-auto max-h-[800px] prose-custom scrollbar-premium">
            <ReactMarkdown 
              remarkPlugins={[remarkMath]} 
              rehypePlugins={[rehypeKatex]}
            >
              {content}
            </ReactMarkdown>
          </div>
          
          <div className="px-8 py-4 bg-muted/30 border-t border-white/5 flex items-center justify-between">
             <div className="flex items-center gap-2 text-xs text-muted-foreground">
               <FileText className="w-3.5 h-3.5" />
               <span>Type: <span className="capitalize font-medium text-foreground">{type}</span></span>
             </div>
             <span className="text-xs text-muted-foreground italic">Generated by AI Study Helper</span>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

import { BrainCircuit } from "lucide-react";
